name: CI - Build and push Caddy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - docker/caddy/**
      - .github/workflows/ci-caddy-pr.yml

permissions:
  contents: write
  pull-requests: write


jobs:
  build-caddy:
    name: Build Caddy
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/caddy
            ghcr.io/${{ github.repository }}/caddy
            ghcr.io/${{ github.repository_owner }}/caddy
          tags: |
            type=ref,event=pr

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker/caddy/
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/caddy:pr-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/caddy:pr-cache,mode=max
  
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
  dependabot:
    needs: [build-caddy]
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
