name: CI - Build and push Caddy

on:
  push:
    branches: [ main ]
    paths:
      - docker/caddy/**
      - .github/workflows/ci-caddy.yml
  workflow_dispatch:

jobs:
  build-caddy:
    name: Build Caddy
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/caddy
            ghcr.io/${{ github.repository }}/caddy
            ghcr.io/${{ github.repository_owner }}/caddy
          tags: |
            type=raw,value={{date 'YYYY.MM.DD-HHmmss'}}
            type=raw,value=latest
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/caddy/
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/caddy:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/caddy:cache,mode=max
