name: CI - Build and push Toolkit

on:
  push:
    branches: [ main ]
    paths:
      - ./docker/toolkit
  workflow_dispatch:

jobs:
  build-toolkit:
    name: Build Toolkit
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/docker-toolkit
            ghcr.io/${{ github.repository }}/docker-toolkit
            ghcr.io/${{ github.repository_owner }}/docker-toolkit
          tags: |
            type=raw,value={{date 'YYYY.MM.DD-HHmmss'}}
            type=raw,value=latest
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker/toolkit/
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/docker-toolkit:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/docker-toolkit:cache,mode=max
