name: CI - Build Toolkit

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write


jobs:
  build-toolkit:
    name: Build Toolkit
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/docker-toolkit
            ghcr.io/${{ github.repository }}/docker-toolkit
            ghcr.io/${{ github.repository_owner }}/docker-toolkit
          tags: |
            type=ref,event=pr

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker/toolkit/
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/docker-toolkit:pr-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/docker-toolkit:pr-cache,mode=max
      
      - name: Test Docker image
        run: |
          docker run -d -p 8443:8443 ghcr.io/${{ github.repository_owner }}/docker-toolkit:pr-${{ github.event.pull_request.number }}
          ./.github/workflows/scripts/test-toolkit-docker-image.sh
  
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
  dependabot:
    needs: [build-toolkit]
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --auto --merge ${{ github.event.pull_request.html_url }}