name: CI - Build Toolkit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-toolkit:
    name: Build Toolkit
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/docker-toolkit
            ghcr.io/${{ github.repository }}/docker-toolkit
            ghcr.io/${{ github.repository_owner }}/docker-toolkit
          tags: |
            type=ref,event=pr

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/toolkit/
          push: ${{ vars.DEBUG == 'true' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/docker-toolkit:pr-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/docker-toolkit:pr-cache,mode=max